### ISSUE TITLE
Some questions for v. 1.2

### ISSUE THREAD

**Issue by Heinz-Olaf** [berzerk0/Probable-Wordlists#23]
Hi,

i have any questions. You have a lot of funny things in the list:

1) Passwords from 1 to 4 characters - with brute-force goes fast and saves approx. 370 MB

2) Passwords consisting only of numbers. Up to 9 characters with brute-force is faster. Above 10 characters such passwords are rather rare. You can also save 2 GB (save it in a separate file).

3) E-mails are rarely used as passwords.

4) Passwords consisting only of special characters. Are also rather rare.

5) Very long lines with code fragments and MD5 hashes (32 characters and longer). The most are definitely not passwords, but garbage, the hackers in their password-lists not eliminated because too lazy.

6) Special characters a-la "&036;" in passwords. Most of them have been created between UTF-8, Win and UTF-16 in the event of a wrong configuration. You have to convert such things.

Regards,

John

**Comment by berzerk0** [comment]
John,

First of all, thanks for doing such a deep dive of the lists!

I'm not sure what you mean by points __1 and 2__. What are you comparing here?

 __3 and 4__: The files in these lists come straight from the sources, other than that for this release I removed non-ASCII characters. If passwords took the form of all special characters or full email addresses, thats simply because of how they were found in the files.
- In fact, I wouldn't be surprised if somewhere, there are people who think email addresses make good passwords. They're long, they use special characters, and may already be committed to memory. Personally, I don't think they ARE good passwords, since they by definition need to be known by other people. However, 2nd most common password is *password* so we know people use insecure passwords.


__5__: You've found one of the main distinctions between version 1 and the upcoming version 2. I have learned an awful lot since version 1 - including how to recognize and filter out hashes. However, I am not 100% sure that I want to leave them out of analysis entirely; there is a chance they are still passwords, although this chance is very slim. My logic/methodology is this:
- Search Each file for lines that might be/contain hashes with commands like...
```
egrep '^[a-f0-9]{32}\s\*$'   - For MD5 Hashes
egrep '^[a-f0-9]{40}\s\*$' - For SHA-1 Hashes
and more, for commonly used hashing algorithms, including the possibility that a line contains hashes and additional text
```
- Copy these lines in a separate file for processing, but __LEAVE THEM IN THE ORIGINAL__
- I want to leave them in the original because the chance of them being plaintext passwords is very, very slim - so slim that when I create the master list, they will likely only appear once
- Wordlists that I put into the repository only contain lines that appeared two times or more (possibly three times if I judge the 2+ results as being suspect)

__6__: Similar logic applies here for character encoding. This I have to spend more time with,  but will be handled similarly to the hashes

**Comment by Heinz-Olaf** [comment]
**1 an 2**
My 2 first Attacks ALWAYS:
1) Brute-Force with all Symbols from 1 to 4.
2) Brute-Force with all Digits from 5 to 9.
That is why I have no such passwords in my dictionaries. This saves me a bit of space and time.
**3 and 4**
I have never seen a password as e-mail or ONLY with special characters.... But you're also right. That is why I filter such "passwords" from my dictionaries in 2 special dictionaries: "E_Mail_Passes" and "Special_Passes". I use these dictionaries as a last resort. This saves me also a bit of time.
**5**
For Example:
**Row 26220374**
13422768vanelilgiantbb@wmconnect.comwkirkwooddiva2000@hanmail.nTeicha88@Yahrene.thomassin@frechacha1973@orapril_caliendo@aPRIDELARAZA68@TMAIL.lilguera@sbcghexim1hn@cmich.eddiva21@nate.teichbau@tonlipeskov@winamp.runigypmu@tewlind.l@libero.it
**Row 27149482**
12qwacss@vcarlosmiguel@iandunn.ctsmolik@volraltman@bigpond.zglass@comcasporton@sheffieldtomas.geryk@tisxlxpimp6969xlx@aim.ccss1@ultimcarlosmiguel182@gp-k84010.nrmanaia@portugkharris12151953@prodd1248811@rtrtr.srimes@somersetomas.guzdek@volny.cz
**Row29062780**
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345

These are definitely not passwords!

**6**
Ok. I understand.

Thank you for your work! It's great and helpful for me.

**Comment by berzerk0** [comment]
I'll try and weed out lines that don't belong.
Closing.
